### ISSUE TITLE
Trivia Question Structure

### ISSUE THREAD

**Issue by silviascript** [ga-dc/project1#117]
https://github.com/siltastic/trivia-game/blob/master/js/main.js#L60-L75

I created a simple animation that slides in the trivia question from the right. It stops at the center of the browser screen and the user can start the trivia game. Once the user selects an answer, the answered question slides to the left. The next question will slide in from the right. Unfortunately, I am unsure what direction I should take this in terms of the structure (like if/else in a loop). I have written simple pseudocode as a starting point.

``` javascript
// Add an event listener to all <li> tags.
$(".choice").click(function() {
  console.log("this =", this);

  // Match answers to the individual <li> tags.
  var userChoice = $(this).text();
    console.log(userChoice);

  // Loop through all the answers in the "correctAnswers" array.
  for (var i = 0; i < correctAnswers.length; i++) {

  // If the answer is correct ...
  if (correctAnswers[i] === userChoice) {
  // Append the "correct" class.

    // Add 1 point to each correct answer.
    $(".trivia-score").html(function(i, val) {
      return val * 1 + 1;
    });
  };

  // Slide the answered trivia question towards the left.
    // Remove the animation class.
    // Add hide question.

  // Slide the next trivia question from the right.
    // Remove hide class.
    // Add the animation class.
  // Repeat steps until all questions are answered.

};
console.log("User has chosen.");
```

**Comment by jshawl** [comment]
I think you can do this by manipulating classes. i.e. each card starts off with the class `.right`. (on the right side of the screen).

When a card is visible, it doesn't have the right class.

When a card slides to the left, it has the `.left` class.

Try making the cards move with class manipulation without the animation just to start

**Comment by adambray** [comment]
My thinking is, you don't need any if or else statements, or a loop, since this should happen on any click on an answer (and you're already in that click listener).

The trick is you'll need to add this class (the animation one) to the parent element that represents the question (since `this` refers to the <li>).

One thing that may help you in doing so is `$(this).closest("some_selector")` which will give you the first ancestor that matches the selector.

The only case you need an `if` may be to detect when you're on the last question.

**Comment by silviascript** [comment]
Thanks for the suggestions, I will work with them!

**Comment by jshawl** [comment]
closing for now please reopen if you'd like to discuss further
